# mypy: ignore-errors
# -*- coding: utf-8 -*-
#
# NVDLA register definitions for direct MMIO register programming.
# Register addresses from allbilly's active ARNVDLA CMOD map
# (ref/hw/cmod/include/arnvdla.uh).
# No KMD needed — registers are written directly to MMIO via /dev/mem.
# This mirrors the rockchip backend's register-command model but with
# NVDLA SDP/BDMA/GLB register addresses.
#
# MMIO base on VP: 0x10200000 (from gen_cfg2c.py)
# DRAM base on VP: 0xC0000000 (from gen_cfg2c.py)

# ---- MMIO base address (configurable via env) ----
import os
NVDLA_MMIO_BASE = int(os.environ.get("NVDLA_MMIO_BASE", "0x10200000"), 0)
NVDLA_MMIO_SIZE = 0x10220000 - 0x10200000  # 0x20000 (128KB)
NVDLA_DRAM_BASE = int(os.environ.get("NVDLA_DRAM_BASE", "0xC0000000"), 0)
NVDLA_DRAM_SIZE = int(os.environ.get("NVDLA_DRAM_SIZE", "0x10000000"), 0)  # 256MB default

# ---- ARNVDLA GLB (global) registers — 0x0000+ ----
NVDLA_GLB_S_INTR_MASK_0 = 0x0004
NVDLA_GLB_S_INTR_SET_0 = 0x0008
NVDLA_GLB_S_INTR_STATUS_0 = 0x000c

# ---- BDMA registers — 0x10000+ ----
NVDLA_BDMA_CFG_SRC_ADDR_LOW_0 = 0x10000
NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0 = 0x10004
NVDLA_BDMA_CFG_DST_ADDR_LOW_0 = 0x10008
NVDLA_BDMA_CFG_DST_ADDR_HIGH_0 = 0x1000c
NVDLA_BDMA_CFG_LINE_0 = 0x10010
NVDLA_BDMA_CFG_CMD_0 = 0x10014
NVDLA_BDMA_CFG_LINE_REPEAT_0 = 0x10018
NVDLA_BDMA_CFG_SRC_LINE_0 = 0x1001c
NVDLA_BDMA_CFG_DST_LINE_0 = 0x10020
NVDLA_BDMA_CFG_SURF_REPEAT_0 = 0x10024
NVDLA_BDMA_CFG_SRC_SURF_0 = 0x10028
NVDLA_BDMA_CFG_DST_SURF_0 = 0x1002c
NVDLA_BDMA_CFG_OP_0 = 0x10030
NVDLA_BDMA_CFG_LAUNCH0_0 = 0x10034
NVDLA_BDMA_CFG_LAUNCH1_0 = 0x10038
NVDLA_BDMA_CFG_STATUS_0 = 0x1003c
NVDLA_BDMA_STATUS_0 = 0x10040

# ---- SDP RDMA registers — ARNVDLA 0xa000+ ----
NVDLA_SDP_RDMA_S_POINTER_0 = 0xa004
NVDLA_SDP_RDMA_D_OP_ENABLE_0 = 0xa008
NVDLA_SDP_RDMA_D_DATA_CUBE_WIDTH_0 = 0xa00c
NVDLA_SDP_RDMA_D_DATA_CUBE_HEIGHT_0 = 0xa010
NVDLA_SDP_RDMA_D_DATA_CUBE_CHANNEL_0 = 0xa014
NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_LOW_0 = 0xa018
NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_HIGH_0 = 0xa01c
NVDLA_SDP_RDMA_D_SRC_LINE_STRIDE_0 = 0xa020
NVDLA_SDP_RDMA_D_SRC_SURFACE_STRIDE_0 = 0xa024
NVDLA_SDP_RDMA_D_BRDMA_CFG_0 = 0xa028
NVDLA_SDP_RDMA_D_BS_BASE_ADDR_LOW_0 = 0xa02c
NVDLA_SDP_RDMA_D_BS_BASE_ADDR_HIGH_0 = 0xa030
NVDLA_SDP_RDMA_D_NRDMA_CFG_0 = 0xa040
NVDLA_SDP_RDMA_D_BN_BASE_ADDR_LOW_0 = 0xa044
NVDLA_SDP_RDMA_D_BN_BASE_ADDR_HIGH_0 = 0xa048
NVDLA_SDP_RDMA_D_ERDMA_CFG_0 = 0xa058
NVDLA_SDP_RDMA_D_EW_BASE_ADDR_LOW_0 = 0xa05c
NVDLA_SDP_RDMA_D_EW_BASE_ADDR_HIGH_0 = 0xa060
NVDLA_SDP_RDMA_D_EW_LINE_STRIDE_0 = 0xa064
NVDLA_SDP_RDMA_D_EW_SURFACE_STRIDE_0 = 0xa068
NVDLA_SDP_RDMA_D_FEATURE_MODE_CFG_0 = 0xa070
NVDLA_SDP_RDMA_D_SRC_DMA_CFG_0 = 0xa074

# ---- SDP registers — ARNVDLA 0xb000+ ----
NVDLA_SDP_S_POINTER_0 = 0xb004
NVDLA_SDP_D_OP_ENABLE_0 = 0xb038
NVDLA_SDP_D_DATA_CUBE_WIDTH_0 = 0xb03c
NVDLA_SDP_D_DATA_CUBE_HEIGHT_0 = 0xb040
NVDLA_SDP_D_DATA_CUBE_CHANNEL_0 = 0xb044
NVDLA_SDP_D_DST_BASE_ADDR_LOW_0 = 0xb048
NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0 = 0xb04c
NVDLA_SDP_D_DST_LINE_STRIDE_0 = 0xb050
NVDLA_SDP_D_DST_SURFACE_STRIDE_0 = 0xb054
NVDLA_SDP_D_DP_BS_CFG_0 = 0xb058
NVDLA_SDP_D_DP_BS_ALU_CFG_0 = 0xb05c
NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0 = 0xb060
NVDLA_SDP_D_DP_BS_MUL_CFG_0 = 0xb064
NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0 = 0xb068
NVDLA_SDP_D_DP_BN_CFG_0 = 0xb06c
NVDLA_SDP_D_DP_BN_ALU_CFG_0 = 0xb070
NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0 = 0xb074
NVDLA_SDP_D_DP_BN_MUL_CFG_0 = 0xb078
NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0 = 0xb07c
NVDLA_SDP_D_DP_EW_CFG_0 = 0xb080
NVDLA_SDP_D_DP_EW_ALU_CFG_0 = 0xb084
NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0 = 0xb088
NVDLA_SDP_D_DP_EW_MUL_CFG_0 = 0xb098
NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0 = 0xb09c
NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0 = 0xb0ac
NVDLA_SDP_D_FEATURE_MODE_CFG_0 = 0xb0b0
NVDLA_SDP_D_DST_DMA_CFG_0 = 0xb0b4
NVDLA_SDP_D_DATA_FORMAT_0 = 0xb0bc
NVDLA_SDP_D_CVT_OFFSET_0 = 0xb0c0
NVDLA_SDP_D_CVT_SCALE_0 = 0xb0c4
NVDLA_SDP_D_CVT_SHIFT_0 = 0xb0c8
NVDLA_SDP_D_STATUS_0 = 0xb0cc

# ---- BDMA status done bit ----
NVDLA_BDMA_STATUS_DONE = 0x10040  # same as NVDLA_BDMA_STATUS_0

__all__ = [
  'NVDLA_MMIO_BASE', 'NVDLA_MMIO_SIZE', 'NVDLA_DRAM_BASE', 'NVDLA_DRAM_SIZE',
  'NVDLA_GLB_S_INTR_MASK_0', 'NVDLA_GLB_S_INTR_SET_0', 'NVDLA_GLB_S_INTR_STATUS_0',
  'NVDLA_BDMA_CFG_SRC_ADDR_LOW_0', 'NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0',
  'NVDLA_BDMA_CFG_DST_ADDR_LOW_0', 'NVDLA_BDMA_CFG_DST_ADDR_HIGH_0',
  'NVDLA_BDMA_CFG_LINE_0', 'NVDLA_BDMA_CFG_CMD_0', 'NVDLA_BDMA_CFG_LINE_REPEAT_0',
  'NVDLA_BDMA_CFG_SRC_LINE_0', 'NVDLA_BDMA_CFG_DST_LINE_0',
  'NVDLA_BDMA_CFG_SURF_REPEAT_0', 'NVDLA_BDMA_CFG_SRC_SURF_0',
  'NVDLA_BDMA_CFG_DST_SURF_0', 'NVDLA_BDMA_CFG_OP_0',
  'NVDLA_BDMA_CFG_LAUNCH0_0', 'NVDLA_BDMA_CFG_LAUNCH1_0',
  'NVDLA_BDMA_CFG_STATUS_0', 'NVDLA_BDMA_STATUS_0', 'NVDLA_BDMA_STATUS_DONE',
  'NVDLA_SDP_RDMA_S_POINTER_0', 'NVDLA_SDP_RDMA_D_OP_ENABLE_0',
  'NVDLA_SDP_RDMA_D_DATA_CUBE_WIDTH_0', 'NVDLA_SDP_RDMA_D_DATA_CUBE_HEIGHT_0',
  'NVDLA_SDP_RDMA_D_DATA_CUBE_CHANNEL_0',
  'NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_SRC_LINE_STRIDE_0', 'NVDLA_SDP_RDMA_D_SRC_SURFACE_STRIDE_0',
  'NVDLA_SDP_RDMA_D_BRDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_BS_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_BS_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_NRDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_BN_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_BN_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_ERDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_EW_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_EW_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_EW_LINE_STRIDE_0', 'NVDLA_SDP_RDMA_D_EW_SURFACE_STRIDE_0',
  'NVDLA_SDP_RDMA_D_FEATURE_MODE_CFG_0', 'NVDLA_SDP_RDMA_D_SRC_DMA_CFG_0',
  'NVDLA_SDP_S_POINTER_0', 'NVDLA_SDP_D_OP_ENABLE_0',
  'NVDLA_SDP_D_DATA_CUBE_WIDTH_0', 'NVDLA_SDP_D_DATA_CUBE_HEIGHT_0',
  'NVDLA_SDP_D_DATA_CUBE_CHANNEL_0',
  'NVDLA_SDP_D_DST_BASE_ADDR_LOW_0', 'NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_D_DST_LINE_STRIDE_0', 'NVDLA_SDP_D_DST_SURFACE_STRIDE_0',
  'NVDLA_SDP_D_DP_BS_CFG_0', 'NVDLA_SDP_D_DP_BS_ALU_CFG_0',
  'NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0', 'NVDLA_SDP_D_DP_BS_MUL_CFG_0',
  'NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_BN_CFG_0', 'NVDLA_SDP_D_DP_BN_ALU_CFG_0',
  'NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0', 'NVDLA_SDP_D_DP_BN_MUL_CFG_0',
  'NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_CFG_0', 'NVDLA_SDP_D_DP_EW_ALU_CFG_0',
  'NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_MUL_CFG_0', 'NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0',
  'NVDLA_SDP_D_FEATURE_MODE_CFG_0', 'NVDLA_SDP_D_DST_DMA_CFG_0',
  'NVDLA_SDP_D_DATA_FORMAT_0',
  'NVDLA_SDP_D_CVT_OFFSET_0', 'NVDLA_SDP_D_CVT_SCALE_0', 'NVDLA_SDP_D_CVT_SHIFT_0',
  'NVDLA_SDP_D_STATUS_0',
]
