# mypy: ignore-errors
# -*- coding: utf-8 -*-
#
# NVDLA register definitions for direct MMIO register programming.
# Register addresses from nv_small spec (ref/nvdla/examples/REG_MAP.py).
# No KMD needed — registers are written directly to MMIO via /dev/mem.
# This mirrors the rockchip backend's register-command model but with
# NVDLA SDP/BDMA/GLB register addresses.
#
# MMIO base on VP: 0x10200000 (from gen_cfg2c.py)
# DRAM base on VP: 0xC0000000 (from gen_cfg2c.py)

# ---- MMIO base address (configurable via env) ----
import os
NVDLA_MMIO_BASE = int(os.environ.get("NVDLA_MMIO_BASE", "0x10200000"), 0)
NVDLA_MMIO_SIZE = 0x10220000 - 0x10200000  # 0x20000 (128KB)
NVDLA_DRAM_BASE = int(os.environ.get("NVDLA_DRAM_BASE", "0xC0000000"), 0)
NVDLA_DRAM_SIZE = int(os.environ.get("NVDLA_DRAM_SIZE", "0x10000000"), 0)  # 256MB default

# ---- GLB (global) registers — 0x1000+ ----
NVDLA_GLB_S_INTR_MASK_0 = 0x1004
NVDLA_GLB_S_INTR_SET_0 = 0x1008
NVDLA_GLB_S_INTR_STATUS_0 = 0x100c

# ---- BDMA registers — 0x10000+ ----
NVDLA_BDMA_CFG_SRC_ADDR_LOW_0 = 0x10000
NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0 = 0x10004
NVDLA_BDMA_CFG_DST_ADDR_LOW_0 = 0x10008
NVDLA_BDMA_CFG_DST_ADDR_HIGH_0 = 0x1000c
NVDLA_BDMA_CFG_LINE_0 = 0x10010
NVDLA_BDMA_CFG_CMD_0 = 0x10014
NVDLA_BDMA_CFG_LINE_REPEAT_0 = 0x10018
NVDLA_BDMA_CFG_SRC_LINE_0 = 0x1001c
NVDLA_BDMA_CFG_DST_LINE_0 = 0x10020
NVDLA_BDMA_CFG_SURF_REPEAT_0 = 0x10024
NVDLA_BDMA_CFG_SRC_SURF_0 = 0x10028
NVDLA_BDMA_CFG_DST_SURF_0 = 0x1002c
NVDLA_BDMA_CFG_OP_0 = 0x10030
NVDLA_BDMA_CFG_LAUNCH0_0 = 0x10034
NVDLA_BDMA_CFG_LAUNCH1_0 = 0x10038
NVDLA_BDMA_CFG_STATUS_0 = 0x1003c
NVDLA_BDMA_STATUS_0 = 0x10040

# ---- SDP RDMA registers — 0x8000+ ----
NVDLA_SDP_RDMA_S_POINTER_0 = 0x8004
NVDLA_SDP_RDMA_D_OP_ENABLE_0 = 0x8008
NVDLA_SDP_RDMA_D_DATA_CUBE_WIDTH_0 = 0x800c
NVDLA_SDP_RDMA_D_DATA_CUBE_HEIGHT_0 = 0x8010
NVDLA_SDP_RDMA_D_DATA_CUBE_CHANNEL_0 = 0x8014
NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_LOW_0 = 0x8018
NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_HIGH_0 = 0x801c
NVDLA_SDP_RDMA_D_BRDMA_CFG_0 = 0x8028
NVDLA_SDP_RDMA_D_BS_BASE_ADDR_LOW_0 = 0x802c
NVDLA_SDP_RDMA_D_BS_BASE_ADDR_HIGH_0 = 0x8030
NVDLA_SDP_RDMA_D_NRDMA_CFG_0 = 0x8040
NVDLA_SDP_RDMA_D_BN_BASE_ADDR_LOW_0 = 0x8044
NVDLA_SDP_RDMA_D_BN_BASE_ADDR_HIGH_0 = 0x8048
NVDLA_SDP_RDMA_D_ERDMA_CFG_0 = 0x8058
NVDLA_SDP_RDMA_D_EW_BASE_ADDR_LOW_0 = 0x805c
NVDLA_SDP_RDMA_D_EW_BASE_ADDR_HIGH_0 = 0x8060
NVDLA_SDP_RDMA_D_FEATURE_MODE_CFG_0 = 0x8070

# ---- SDP registers — 0x9000+ ----
NVDLA_SDP_S_POINTER_0 = 0x9004
NVDLA_SDP_D_OP_ENABLE_0 = 0x9038
NVDLA_SDP_D_DATA_CUBE_WIDTH_0 = 0x903c
NVDLA_SDP_D_DATA_CUBE_HEIGHT_0 = 0x9040
NVDLA_SDP_D_DATA_CUBE_CHANNEL_0 = 0x9044
NVDLA_SDP_D_DST_BASE_ADDR_LOW_0 = 0x9048
NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0 = 0x904c
NVDLA_SDP_D_DST_LINE_STRIDE_0 = 0x9050
NVDLA_SDP_D_DST_SURFACE_STRIDE_0 = 0x9054
NVDLA_SDP_D_DP_BS_CFG_0 = 0x9058
NVDLA_SDP_D_DP_BS_ALU_CFG_0 = 0x905c
NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0 = 0x9060
NVDLA_SDP_D_DP_BS_MUL_CFG_0 = 0x9064
NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0 = 0x9068
NVDLA_SDP_D_DP_BN_CFG_0 = 0x906c
NVDLA_SDP_D_DP_BN_ALU_CFG_0 = 0x9070
NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0 = 0x9074
NVDLA_SDP_D_DP_BN_MUL_CFG_0 = 0x9078
NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0 = 0x907c
NVDLA_SDP_D_DP_EW_CFG_0 = 0x9080
NVDLA_SDP_D_DP_EW_ALU_CFG_0 = 0x9084
NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0 = 0x9088
NVDLA_SDP_D_DP_EW_MUL_CFG_0 = 0x9098
NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0 = 0x909c
NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0 = 0x90ac
NVDLA_SDP_D_FEATURE_MODE_CFG_0 = 0x90b0
NVDLA_SDP_D_DST_DMA_CFG_0 = 0x90b4
NVDLA_SDP_D_DATA_FORMAT_0 = 0x90bc
NVDLA_SDP_D_CVT_OFFSET_0 = 0x90c0
NVDLA_SDP_D_CVT_SCALE_0 = 0x90c4
NVDLA_SDP_D_CVT_SHIFT_0 = 0x90c8
NVDLA_SDP_D_STATUS_0 = 0x90cc

# ---- BDMA status done bit ----
NVDLA_BDMA_STATUS_DONE = 0x10040  # same as NVDLA_BDMA_STATUS_0

__all__ = [
  'NVDLA_MMIO_BASE', 'NVDLA_MMIO_SIZE', 'NVDLA_DRAM_BASE', 'NVDLA_DRAM_SIZE',
  'NVDLA_GLB_S_INTR_MASK_0', 'NVDLA_GLB_S_INTR_SET_0', 'NVDLA_GLB_S_INTR_STATUS_0',
  'NVDLA_BDMA_CFG_SRC_ADDR_LOW_0', 'NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0',
  'NVDLA_BDMA_CFG_DST_ADDR_LOW_0', 'NVDLA_BDMA_CFG_DST_ADDR_HIGH_0',
  'NVDLA_BDMA_CFG_LINE_0', 'NVDLA_BDMA_CFG_CMD_0', 'NVDLA_BDMA_CFG_LINE_REPEAT_0',
  'NVDLA_BDMA_CFG_SRC_LINE_0', 'NVDLA_BDMA_CFG_DST_LINE_0',
  'NVDLA_BDMA_CFG_SURF_REPEAT_0', 'NVDLA_BDMA_CFG_SRC_SURF_0',
  'NVDLA_BDMA_CFG_DST_SURF_0', 'NVDLA_BDMA_CFG_OP_0',
  'NVDLA_BDMA_CFG_LAUNCH0_0', 'NVDLA_BDMA_CFG_LAUNCH1_0',
  'NVDLA_BDMA_CFG_STATUS_0', 'NVDLA_BDMA_STATUS_0', 'NVDLA_BDMA_STATUS_DONE',
  'NVDLA_SDP_RDMA_S_POINTER_0', 'NVDLA_SDP_RDMA_D_OP_ENABLE_0',
  'NVDLA_SDP_RDMA_D_DATA_CUBE_WIDTH_0', 'NVDLA_SDP_RDMA_D_DATA_CUBE_HEIGHT_0',
  'NVDLA_SDP_RDMA_D_DATA_CUBE_CHANNEL_0',
  'NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_SRC_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_BRDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_BS_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_BS_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_NRDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_BN_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_BN_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_ERDMA_CFG_0',
  'NVDLA_SDP_RDMA_D_EW_BASE_ADDR_LOW_0', 'NVDLA_SDP_RDMA_D_EW_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_RDMA_D_FEATURE_MODE_CFG_0',
  'NVDLA_SDP_S_POINTER_0', 'NVDLA_SDP_D_OP_ENABLE_0',
  'NVDLA_SDP_D_DATA_CUBE_WIDTH_0', 'NVDLA_SDP_D_DATA_CUBE_HEIGHT_0',
  'NVDLA_SDP_D_DATA_CUBE_CHANNEL_0',
  'NVDLA_SDP_D_DST_BASE_ADDR_LOW_0', 'NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0',
  'NVDLA_SDP_D_DST_LINE_STRIDE_0', 'NVDLA_SDP_D_DST_SURFACE_STRIDE_0',
  'NVDLA_SDP_D_DP_BS_CFG_0', 'NVDLA_SDP_D_DP_BS_ALU_CFG_0',
  'NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0', 'NVDLA_SDP_D_DP_BS_MUL_CFG_0',
  'NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_BN_CFG_0', 'NVDLA_SDP_D_DP_BN_ALU_CFG_0',
  'NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0', 'NVDLA_SDP_D_DP_BN_MUL_CFG_0',
  'NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_CFG_0', 'NVDLA_SDP_D_DP_EW_ALU_CFG_0',
  'NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_MUL_CFG_0', 'NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0',
  'NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0',
  'NVDLA_SDP_D_FEATURE_MODE_CFG_0', 'NVDLA_SDP_D_DST_DMA_CFG_0',
  'NVDLA_SDP_D_DATA_FORMAT_0',
  'NVDLA_SDP_D_CVT_OFFSET_0', 'NVDLA_SDP_D_CVT_SCALE_0', 'NVDLA_SDP_D_CVT_SHIFT_0',
  'NVDLA_SDP_D_STATUS_0',
]
