#!/usr/bin/env python3
import hashlib, math, pathlib, struct

SIZE, INDEX_SCALE, OUTPUT_SCALE, MINUS_EXP = 513, 8192.0, 8192.0, 13
STEP = 32.0 / INDEX_SCALE
values = [max(-32768, min(32767, round(math.exp2((-(512-i)*STEP) if table == 0 else i*STEP) * OUTPUT_SCALE)))
          for table in range(2) for i in range(SIZE)]
payload = struct.pack(f"<{len(values)}h", *values)
sha = hashlib.sha256(payload).hexdigest()
def half(value:float) -> float: return struct.unpack("<e", struct.pack("<e", value))[0]
errors = []
for bits in range(1 << 16):
  x = struct.unpack("<e", struct.pack("<H", bits))[0]
  if not math.isfinite(x) or not -2 <= x <= 2: continue
  position, base = ((x+2)*256, 0) if x < 0 else (x*256, SIZE)
  index = min(511, max(0, math.floor(position)))
  got = half(((1-(position-index))*values[base+index] + (position-index)*values[base+index+1]) / OUTPUT_SCALE)
  reference = math.exp2(x)
  errors.append((abs(got-reference), abs(got-reference)/reference))
rows = "\n".join("  " + ", ".join(map(str, values[i:i+16])) + "," for i in range(0, len(values), 16))
output = f'''# generated by extra/rockchip/gen_lut.py; do not edit
from enum import IntEnum
class RKLUT(IntEnum): EXP2 = 1
RK_LUT_SCHEMA = 1
RK_LUT_EXP2_SHA256 = "{sha}"
RK_LUT_EXP2_DOMAIN = (-2.0, 2.0)
RK_LUT_EXP2_ENTRIES = {SIZE}
RK_LUT_EXP2_BN_MUL = {struct.unpack('<H', struct.pack('<e', INDEX_SCALE))[0]}
RK_LUT_EXP2_MINUS_EXP = {MINUS_EXP}
RK_LUT_EXP2_VERIFIED_INPUTS = {len(errors)}
RK_LUT_EXP2_SIM_MAX_ABS_ERROR = {max(x[0] for x in errors)!r}
RK_LUT_EXP2_SIM_MAX_REL_ERROR = {max(x[1] for x in errors)!r}
RK_LUT_EXP2 = (\n{rows}\n)\n'''
pathlib.Path(__file__).parents[2].joinpath("tinygrad/runtime/autogen/rockchip_lut.py").write_text(output)
