#!/usr/bin/env python3
import hashlib, math, pathlib, struct
from dataclasses import dataclass
from typing import Callable

SIZE = 513
def half(value:float) -> float: return struct.unpack("<e", struct.pack("<e", value))[0]
def hardswish(x:float) -> float: return x * min(6.0, max(0.0, x+3.0)) / 6.0

@dataclass(frozen=True)
class LUT:
  name: str
  function: Callable[[float], float]
  domain: float
  index_scale: float
  output_scale: float
  minus_exp: int
  replace_zero: bool = False

LUTS = (
  LUT("EXP2", math.exp2, 2.0, 8192.0, 8192.0, 13),
  LUT("HARDSWISH", hardswish, 2.0, 8192.0, 16384.0, 14, True),
  LUT("HARDSWISH_LOCAL", lambda z: hardswish(half(z/16))*16, 2.0, 8192.0, 32768.0, 15, True),
)

def compile_lut(spec:LUT) -> tuple[list[int], str]:
  step = 32.0/spec.index_scale
  values = []
  for table in range(2):
    for i in range(SIZE):
      x = (-(512-i) if table == 0 else i)*step
      raw = max(-32768, min(32767, round(spec.function(x)*spec.output_scale)))
      values.append(1 if spec.replace_zero and raw == 0 else raw)
  payload = struct.pack(f"<{len(values)}h", *values)
  return values, hashlib.sha256(payload).hexdigest()

parts = ["# generated by extra/rockchip/gen_lut.py; do not edit", "from enum import IntEnum",
         "class RKLUT(IntEnum):\n  EXP2 = 1\n  HARDSWISH = 2\n  HARDSWISH_LOCAL = 3", "RK_LUT_SCHEMA = 2"]
for spec in LUTS:
  values, sha = compile_lut(spec)
  prefix = f"RK_LUT_{spec.name}"
  rows = "\n".join("  " + ", ".join(map(str, values[i:i+16])) + "," for i in range(0, len(values), 16))
  parts += [f'{prefix}_SHA256 = "{sha}"', f"{prefix}_DOMAIN = (-{spec.domain!r}, {spec.domain!r})",
            f"{prefix}_ENTRIES = {SIZE}", f"{prefix}_BN_MUL = {struct.unpack('<H', struct.pack('<e', spec.index_scale))[0]}",
            f"{prefix}_MINUS_EXP = {spec.minus_exp}", f"{prefix} = (\n{rows}\n)"]

# Preserve the exhaustive EXP2 simulator contract used by the compiler tests.
exp_values, _ = compile_lut(LUTS[0])
errors = []
for bits in range(1 << 16):
  x = struct.unpack("<e", struct.pack("<H", bits))[0]
  if not math.isfinite(x) or not -2 <= x <= 2: continue
  position, base = ((x+2)*256, 0) if x < 0 else (x*256, SIZE)
  index = min(511, max(0, math.floor(position)))
  got = half(((1-(position-index))*exp_values[base+index] + (position-index)*exp_values[base+index+1]) / 8192)
  errors.append((abs(got-math.exp2(x)), abs(got-math.exp2(x))/math.exp2(x)))
parts[8:8] = [f"RK_LUT_EXP2_VERIFIED_INPUTS = {len(errors)}", f"RK_LUT_EXP2_SIM_MAX_ABS_ERROR = {max(x[0] for x in errors)!r}",
              f"RK_LUT_EXP2_SIM_MAX_REL_ERROR = {max(x[1] for x in errors)!r}"]
pathlib.Path(__file__).parents[2].joinpath("tinygrad/runtime/autogen/rockchip_lut.py").write_text("\n".join(parts)+"\n")
